### ISSUE TITLE
[!] Upgrading Windows shell is not implemented yet.

### ISSUE THREAD

**Issue by Mag1cByt3s** [brightio/penelope#20]
Is there any plan to implement the feature for automatically upgrading Windows shells to full PTYs?

I just tried out penelope again and so far i really like it but the feature for Windows machines is still lacking.

**Comment by xvk1t1** [comment]
It will be awesome!

**Comment by brightio** [comment]
Hi @Mag1cByt3s. Upgrading Windows shells to full PTYs is in the plans, but it will take long time because it's quite complicated. What will be done sooner is adding readline support. I'll share the commit once it's ready. Thanks!

**Comment by Mag1cByt3s** [comment]
Thanks. I'm looking forward to it!

**Comment by brightio** [comment]
@Mag1cByt3s, readline support added with commit ef13f81

**Comment by Mag1cByt3s** [comment]
Thanks!
