### ISSUE TITLE
can this work as python http.server?

### ISSUE THREAD

**Issue by DaddyBigFish** [brightio/penelope#25]
I want to use this to upload files without the shell is that possible?

**Comment by brightio** [comment]
This is already in the roadmap. I will connect the commit with this Issue once it's ready.

**Comment by brightio** [comment]
Hi @DaddyBigFish,

Here is the commit that adds this feature: 3ee383f

You can use it like `./penelope.py -s` to serve the current directory or like `./penelope.py -s /etc /tmp /etc/issue` to serve multiple files and directories. You can use also the -p and -i switches for port and interface respectively.

Please have a look and tell me if you find any issues.

Thank you

**Comment by DaddyBigFish** [comment]
Awesome nice addition man!
