### ISSUE TITLE
Log file encoding

### ISSUE THREAD

**Issue by funkyfliam** [brightio/penelope#29]
What file encoding do the log files use? Any way to get it to log without any formatting escape codes?
Thanks!

![image](https://github.com/user-attachments/assets/1cf71e3e-cf6e-45d8-acf9-237ef6ecc5f7)

**Comment by brightio** [comment]
Hi @funkyfliam. These are ANSII escape codes for coloring. You can "cat" the file to see the colored timestamp, or run penelope with -T to log without timestamps.

**Comment by funkyfliam** [comment]
Thank you very much for the fast response. Would an additional option be possible to log without color codes? I'd like to keep the timestamps in the logs where possible. Not a massive problem if it's too much effort - can strip them externally in post processing

**Comment by brightio** [comment]
That's a good suggestion. I reopened the issue and i will notify you once this feature is ready.

**Comment by brightio** [comment]
@funkyfliam the option is implemented. Just use the -CT switch.
