### ISSUE TITLE
Error on line 438

### ISSUE THREAD

**Issue by grisuno** [brightio/penelope#31]
Issue Description
I encountered a NameError while executing the script located at /home/gris/tools/penelope/penelope.py. The error occurs in the cmdloop method when it attempts to call the preloop function.

Error Traceback
arduino
Copiar código
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/$USER/tools/penelope/penelope.py", line 349, in cmdloop
    self.preloop()
  File "/home/$USER/tools/penelope/penelope.py", line 438, in preloop
    __class__.load_history(options.cmd_histfile)
                           ^^^^^^^
NameError: name 'options' is not defined. Did you mean: 'Options'?
Details
The NameError indicates that the variable options is not defined in the current scope. The intended usage seems to be Options.cmd_histfile, which suggests that options was expected to be an instance of the Options class or similar.
Upon encountering this error, the script enters an infinite loop, and I am forced to terminate it using killall.

**Comment by brightio** [comment]
Hi @grisuno, thanks for reporting this. I can't reproduce this error. Can you please tell me how you execute the script (arguments etc)?

**Comment by grisuno** [comment]
without arguments, in a parrot 6.1

![image](https://github.com/user-attachments/assets/a20b6be2-fc93-4f0b-8e22-b6e7b8d4cd3c)

**Comment by brightio** [comment]
I tried this on Parrot 6.1 and I can't reproduce it. Can you please send me a screenshot of the very first exceptions?

**Comment by grisuno** [comment]
![image](https://github.com/user-attachments/assets/1f18851a-7bb5-483a-8ca2-657a9517dacf)

The script enters an infinite loop, continuously displaying the same error message. It keeps repeating the last error, and I have to manually terminate the process using kill -9.

Error details:

python penelope.py

Oops...🐞
────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/gris/tools/penelope/penelope.py", line 4282, in <module>
    options = Options()
              ^^^^^^^^^
  File "/home/gris/tools/penelope/penelope.py", line 4194, in __init__
    self.basedir = Path(pwd.getpwuid(GID).pw_dir) / f'.{__program__}'
                        ^^^^^^^^^^^^^^^^^
KeyError: 'getpwuid(): uid not found: 1001'
Then, it repeats the following error in a loop:

Oops...🐞
────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gris/tools/penelope/penelope.py", line 349, in cmdloop
    self.preloop()
  File "/home/gris/tools/penelope/penelope.py", line 438, in preloop
    __class__.load_history(options.cmd_histfile)
                           ^^^^^^^
NameError: name 'options' is not defined. Did you mean: 'Options'?
This error keeps repeating indefinitely, and I have to stop the process by force using kill -9.

**Comment by brightio** [comment]
Thank you very much @grisuno for reporting this! Can you please try now to verify that it is fixed?

**Comment by grisuno** [comment]
Thanks you bro, now works :) you are awesome ;)
