### ISSUE TITLE
Feature request - Send interupt

### ISSUE THREAD

**Issue by funkyfliam** [brightio/penelope#32]
Good morning,

Thank you for your excellent work. Would be very keen on being able to send interrupt (i.e. CTRL+C) to a target when in interactive mode. Would be great to be able to cancel a hanging command without having to kill the session.

Thanks!

**Comment by brightio** [comment]
hi @funkyfliam, are you referring to Linux/Windows shells or Penelope's interactive menu?

**Comment by funkyfliam** [comment]
> hi @funkyfliam, are you referring to Linux/Windows shells or Penelope's interactive menu?

Linux/Windows shells

**Comment by funkyfliam** [comment]
Just realised that it does actually send them through correctly. Must've been because of a limitation on the specific connection/shell I had open. Will self close

**Comment by brightio** [comment]
Linux shells: The Ctrl-C works as the shells are upgraded to PTY
Windows shells: Ctrl-C is does not work as the shells are upgraded readline mode. PTY upgrade is not implemented yet as it is far more complex.
Penelope menu: Ctrl-C works. It can stop downloads and uploads however it still has some more glitches which I am currently fixing.
