### ISSUE TITLE
Pipx port issue (not really an issue)

### ISSUE THREAD

**Issue by thinkslynk** [brightio/penelope#35]
I'm mostly writing this so if anyone else searches they'll find this. But just note that you can install this with pipx:
```bash
pipx install git+https://github.com/brightio/penelope.git
```

And it will install 2 commands `penelope` and `penelope.py`. The former command does not, for whatever reason, pass along any command line arguments; so it always uses the default port. But `penelope.py` works as it should. So if anyone else was pulling their hair out over this, just use the `.py` command.

(You can close this issue, unless you want to fix it so that both work fine with pipx, or add a blurb to the README. But it will at least be searchable now in the issues. And thank you for your work on this tool!)

**Comment by stavoxnetworks** [comment]
It took me a minute to realize what you were saying. But you are absolutely right. Installing with pipx causes the command "penelope 9999" to still use port 4444.

![2024-11-23_16-20](https://github.com/user-attachments/assets/6b40689a-969e-41ae-b931-1a598495c520)

You can copy penelope.py from /home/user/.local/bin to /usr/bin and then remove the .py extension. That will eliminate the issue and permit you to use only "penelope 9999"

**Comment by brightio** [comment]
@thinkslynk @stavoxnetworks now it should be fixed. Can you please reinstall it and tell me if it works for you? Thank you!

**Comment by stavoxnetworks** [comment]
@brightio I did and can verify that it resolved the issue. Thanks so much.
