### ISSUE TITLE
Invalid shell from *

### ISSUE THREAD

**Issue by NirLevy98** [brightio/penelope#5]
Hi
When I am trying to connect to the shell through Linux ubuntu 5.11.0-34-generic (using fish shell), it is writing to me: "Invalid shell from"

**Comment by brightio** [comment]
Hello @NirLevy98, thank you very much for your feedback. Could you please tell me more information about this? Also a tcpdump capture would help me identify the issue.

**Comment by NirLevy98** [comment]
Hi,

I added an image that describe my problem
![image](https://user-images.githubusercontent.com/7195780/135724078-4ad8071d-464b-4658-9527-1aa744bf49ca.png)

**Comment by brightio** [comment]
This is normal as you haven't specified the program that you want ncat to execute. You must add `-e /bin/bash` to your ncat command. Please try and tell me the outcome. Thanks!
